language: python
install: 
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
script:
  - black .
  - flake8 --max-line-length=92
  - coverage run --source='.' manage.py test polls
after_script:
  - coveralls
